services:
  web:
    build:
      context: git@github.com:karmic-koalas/sibarita-front.git
      ssh:
        - default
    ports:
      - "80:80"
  api:
    build:
      context: git@github.com:karmic-koalas/sibarita-back.git
      ssh:
        - default
    ports:
      - "3000:3000"
