services:
  web:
    build:
      context: git@github.com:karmic-koalas/sibarita-front.git#main
      ssh: [ "default" ]
    ports:
      - "80:80"
  api:
    build:
      context: git@github.com:karmic-koalas/sibarita-back.git#main
      ssh: [ "default" ]
    env_file:
      - .env
    ports:
      - "3000:3000"
